### ISSUE TITLE
nfrd965.sys is the variant "i" of DuQu, not a part of Stuxnet

### ISSUE THREAD

**Issue by shownadda** [loneicewolf/DUQU#1]
nfrd965.sys is from DuQu and from the variant known as "i", according to securelist. 
I've included some hopefully helpful links on this.
https://hal.inria.fr/hal-00925517/document Analysis on the Driver
https://securelist.com/the-mystery-of-duqu-part-ten/32668/ The post that lists it's variants and their files

**Comment by loneicewolf** [comment]
will take a look at both of your contributions after my exam;  thanks!
Best wishes!
